/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 /*test cai demo*/
package GiaoDien_NhanVien;

import GiaoDien_DangNhap.DangNhapFrame;
import GiaoDien_DangNhap.Main;
import com.sun.javafx.geom.AreaOp;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel; 
import java.nio.file.StandardCopyOption;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Admin
 */
public class B_QuanLyKhoFrame extends javax.swing.JFrame {
static final String url="jdbc:sqlserver://localhost;databaseName=quan_ly_ban_hang;user=sa;password=123";
private String header[]={"Mã nhà sản xuất","Tên nhà sản xuất","Địa chỉ","Số điện thoại","Email","ghi chú","hinh"}; 
private  DefaultTableModel table_nhasanxuat=new DefaultTableModel(header,0);
String filenamepic="";
private ArrayList<B_Nhasanxuat>list=new ArrayList<B_Nhasanxuat>();
int currentindex=-1; 
int index=-1;

    /**
     * Creates new form A_QuanLyKhoFrame
     */
    public B_QuanLyKhoFrame() {
        initComponents();
        ImageIcon ig = new ImageIcon(getClass().getResource("/Img_Icon/iconfram.png"));
        Tabbed.setBackground(new Color(245, 245, 245));
        setIconImage(ig.getImage());
        getContentPane().setBackground(new Color(245, 245, 245));
        setTitle("Quản Lý Kho");
        loadtotable_nhasanxuat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabbed = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtMaDT = new javax.swing.JTextField();
        txtTenDT = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAnhDaiDien = new javax.swing.JLabel();
        btnXoaAnh = new javax.swing.JButton();
        txtChooseFile = new javax.swing.JButton();
        pnltructhuoc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        pnltructhuoc2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboBaoHanhDT = new javax.swing.JComboBox<>();
        txtSoLuongTonDT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cboHDH = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboSimDT = new javax.swing.JComboBox<>();
        cboRamDT = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cboMangDT = new javax.swing.JComboBox<>();
        cboSacDT = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaDT = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDienThoai = new javax.swing.JTable();
        btnNewDT = new javax.swing.JButton();
        btnUpdateDT = new javax.swing.JButton();
        btnDeleteDT = new javax.swing.JButton();
        btnExitDT = new javax.swing.JButton();
        btnFirstDT = new javax.swing.JButton();
        btnPreviousDT = new javax.swing.JButton();
        lblRecorđT = new javax.swing.JLabel();
        lblLenghDT = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblIndexDT = new javax.swing.JLabel();
        btnNextDT = new javax.swing.JButton();
        btnLastDT = new javax.swing.JButton();
        btnAddDT = new javax.swing.JButton();
        jpnNSX = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        txt_dienthoainhasanxuat = new javax.swing.JTextField();
        txt_diachinhasanxuat = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        txt_emailnhasanxuat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_ghichunhasanxuat = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        lblId2 = new javax.swing.JLabel();
        txt_manhasanxuat = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        txt_tennhasanxuat = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lbl_anhdaidiennhasanxuat = new javax.swing.JLabel();
        txtChooseFile1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNSX = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        btnNewNSX = new javax.swing.JButton();
        btnExitNSX = new javax.swing.JButton();
        btnFirstNSX = new javax.swing.JButton();
        btnNextNSX = new javax.swing.JButton();
        btnPreNSX = new javax.swing.JButton();
        btnLastNSX = new javax.swing.JButton();
        txtRecord = new javax.swing.JLabel();
        btnAddNSX = new javax.swing.JButton();
        btnDeleteNSX = new javax.swing.JButton();
        btnUpdateNSX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelThem = new javax.swing.JPanel();
        lblAnhAccount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabbed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtMaDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaDT.setMinimumSize(new java.awt.Dimension(6, 25));

        txtTenDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDT.setMinimumSize(new java.awt.Dimension(6, 25));

        lblId.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/barcode50px.png"))); // NOI18N
        lblId.setText("Mã Điện Thoại* :");

        lblName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/PhoneName50px.png"))); // NOI18N
        lblName.setText("Tên Điện Thoại");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblAnhDaiDien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnXoaAnh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/delete1_30px.png"))); // NOI18N
        btnXoaAnh.setText("Xóa ảnh");
        btnXoaAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAnhActionPerformed(evt);
            }
        });

        txtChooseFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChooseFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/mo_hinh.png"))); // NOI18N
        txtChooseFile.setText("Chọn ảnh");
        txtChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChooseFile))
                .addGap(0, 179, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChooseFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnXoaAnh)
                .addContainerGap())
            .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnltructhuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        pnltructhuoc.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã nhà sản xuất");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá");

        javax.swing.GroupLayout pnltructhuocLayout = new javax.swing.GroupLayout(pnltructhuoc);
        pnltructhuoc.setLayout(pnltructhuocLayout);
        pnltructhuocLayout.setHorizontalGroup(
            pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltructhuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnltructhuocLayout.setVerticalGroup(
            pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltructhuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnltructhuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnltructhuoc2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tình Trạng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        pnltructhuoc2.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bảo Hành");

        cboBaoHanhDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 năm", "2 năm" }));

        javax.swing.GroupLayout pnltructhuoc2Layout = new javax.swing.GroupLayout(pnltructhuoc2);
        pnltructhuoc2.setLayout(pnltructhuoc2Layout);
        pnltructhuoc2Layout.setHorizontalGroup(
            pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltructhuoc2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnltructhuoc2Layout.createSequentialGroup()
                        .addComponent(cboBaoHanhDT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtSoLuongTonDT))
                .addContainerGap())
        );
        pnltructhuoc2Layout.setVerticalGroup(
            pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltructhuoc2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoLuongTonDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnltructhuoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboBaoHanhDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Hệ điều hành:");

        cboHDH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "IOS" }));
        cboHDH.setMaximumSize(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("RAM:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Sim");

        cboSimDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Sim", "2 Sim" }));
        cboSimDT.setMaximumSize(null);

        cboRamDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2GB", "3GB", "4GB", " " }));
        cboRamDT.setMaximumSize(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSimDT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRamDT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboHDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRamDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cboSimDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Mạng di động:  ");

        cboMangDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4G", "5G" }));
        cboMangDT.setMaximumSize(null);

        cboSacDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hỗ trợ sạc nhanh", "Không hỗ trợ" }));
        cboSacDT.setMaximumSize(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Pin, Sạc:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMangDT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboSacDT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboMangDT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cboSacDT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Mô tả");

        txtMoTaDT.setColumns(20);
        txtMoTaDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMoTaDT.setRows(5);
        jScrollPane1.setViewportView(txtMoTaDT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblDienThoai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDienThoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Điện Thoại", "Tên Điện Thoại", "Số Lượng", "Đơn Giá","Mã nhà sản xuất","Bảo hành"
            }
        ));
        tblDienThoai.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblDienThoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDienThoaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDienThoai);

        btnNewDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNewDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/don_dep.png"))); // NOI18N
        btnNewDT.setText("  New");
        btnNewDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewDTMouseExited(evt);
            }
        });

        btnUpdateDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnUpdateDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/cap_nhat.png"))); // NOI18N
        btnUpdateDT.setText("Update");
        btnUpdateDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateDTMouseExited(evt);
            }
        });

        btnDeleteDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDeleteDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/xoa.png"))); // NOI18N
        btnDeleteDT.setText("Delete");
        btnDeleteDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteDTMouseExited(evt);
            }
        });

        btnExitDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExitDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/exit_30px.png"))); // NOI18N
        btnExitDT.setText("Exit");
        btnExitDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitDTMouseExited(evt);
            }
        });

        btnFirstDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnFirstDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/First.png"))); // NOI18N
        btnFirstDT.setText("First");

        btnPreviousDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPreviousDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/lui.png"))); // NOI18N
        btnPreviousDT.setText("Previous");

        lblRecorđT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRecorđT.setText("Record :");

        lblLenghDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLenghDT.setForeground(new java.awt.Color(255, 0, 0));
        lblLenghDT.setText("0");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setText("of");

        lblIndexDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblIndexDT.setForeground(new java.awt.Color(255, 0, 0));
        lblIndexDT.setText("  0");

        btnNextDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNextDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/tien.png"))); // NOI18N
        btnNextDT.setText("Next");

        btnLastDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLastDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/den_cuoi.png"))); // NOI18N
        btnLastDT.setText("Last");

        btnAddDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/them.png"))); // NOI18N
        btnAddDT.setText("Add");
        btnAddDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddDTMouseExited(evt);
            }
        });
        btnAddDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pnltructhuoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pnltructhuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnFirstDT)
                                .addGap(18, 18, 18)
                                .addComponent(btnPreviousDT)
                                .addGap(18, 18, 18)
                                .addComponent(lblRecorđT)
                                .addGap(18, 18, 18)
                                .addComponent(lblIndexDT)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(lblLenghDT)
                                .addGap(27, 27, 27)
                                .addComponent(btnNextDT)
                                .addGap(18, 18, 18)
                                .addComponent(btnLastDT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNewDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnExitDT)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnltructhuoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnltructhuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFirstDT)
                        .addComponent(btnPreviousDT)
                        .addComponent(lblRecorđT)
                        .addComponent(lblIndexDT)
                        .addComponent(lblLenghDT)
                        .addComponent(jLabel27)
                        .addComponent(btnNextDT)
                        .addComponent(btnLastDT))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExitDT)
                        .addComponent(btnDeleteDT)
                        .addComponent(btnUpdateDT)
                        .addComponent(btnAddDT)
                        .addComponent(btnNewDT)))
                .addContainerGap())
        );

        Tabbed.addTab("Quản Lý Sản Phẩm", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liên Hệ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblName2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lblName2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/iconNumber-50px.png"))); // NOI18N
        lblName2.setText("Điện Thoại");

        lblName4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lblName4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/address-50px.png"))); // NOI18N
        lblName4.setText("Địa Chỉ");

        lblName5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lblName5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/email-50px.png"))); // NOI18N
        lblName5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/icons8-more-48.png"))); // NOI18N
        jLabel6.setText("Mô tả");

        txt_ghichunhasanxuat.setColumns(20);
        txt_ghichunhasanxuat.setRows(5);
        jScrollPane4.setViewportView(txt_ghichunhasanxuat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txt_emailnhasanxuat))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txt_diachinhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(txt_dienthoainhasanxuat))))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName4)
                    .addComponent(txt_diachinhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName5)
                    .addComponent(txt_emailnhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txt_dienthoainhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblId2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lblId2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/factory-50px.png"))); // NOI18N
        lblId2.setText("Mã nhà sản xuất");

        lblName3.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lblName3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/PhoneName50px.png"))); // NOI18N
        lblName3.setText("Tên nhà sản xuất");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblId2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_manhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_tennhasanxuat)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId2)
                    .addComponent(txt_manhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(txt_tennhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_anhdaidiennhasanxuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_anhdaidiennhasanxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anhdaidiennhasanxuatMouseClicked(evt);
            }
        });

        txtChooseFile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChooseFile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/mo_hinh.png"))); // NOI18N
        txtChooseFile1.setText("Chọn ảnh");
        txtChooseFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChooseFile1MouseClicked(evt);
            }
        });
        txtChooseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChooseFile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lbl_anhdaidiennhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtChooseFile1)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtChooseFile1)
                .addContainerGap(76, Short.MAX_VALUE))
            .addComponent(lbl_anhdaidiennhasanxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblNSX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblNSX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNSX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhà Sản Xuất", "Tên Nhà Sản Xuất", "Địa Chỉ", "Email","Điện Thoại","Mô tả"
            }
        ));
        tblNSX.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNSXMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNSX);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnNewNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNewNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/don_dep.png"))); // NOI18N
        btnNewNSX.setText("  New");
        btnNewNSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewNSXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewNSXMouseExited(evt);
            }
        });

        btnExitNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExitNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/exit_30px.png"))); // NOI18N
        btnExitNSX.setText("Exit");
        btnExitNSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitNSXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitNSXMouseExited(evt);
            }
        });
        btnExitNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitNSXActionPerformed(evt);
            }
        });

        btnFirstNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnFirstNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/First.png"))); // NOI18N
        btnFirstNSX.setText("First");
        btnFirstNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstNSXActionPerformed(evt);
            }
        });

        btnNextNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNextNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/tien.png"))); // NOI18N
        btnNextNSX.setText("Next");
        btnNextNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextNSXActionPerformed(evt);
            }
        });

        btnPreNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPreNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/lui.png"))); // NOI18N
        btnPreNSX.setText("Previous");
        btnPreNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreNSXActionPerformed(evt);
            }
        });

        btnLastNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLastNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/den_cuoi.png"))); // NOI18N
        btnLastNSX.setText("Last");
        btnLastNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastNSXActionPerformed(evt);
            }
        });

        txtRecord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRecord.setText("Record: 0 of 0");

        btnAddNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/them.png"))); // NOI18N
        btnAddNSX.setText("Add");
        btnAddNSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNSXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNSXMouseExited(evt);
            }
        });
        btnAddNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNSXActionPerformed(evt);
            }
        });

        btnDeleteNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDeleteNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/xoa.png"))); // NOI18N
        btnDeleteNSX.setText("Delete");
        btnDeleteNSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteNSXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteNSXMouseExited(evt);
            }
        });
        btnDeleteNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNSXActionPerformed(evt);
            }
        });

        btnUpdateNSX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnUpdateNSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/cap_nhat.png"))); // NOI18N
        btnUpdateNSX.setText("Update");
        btnUpdateNSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateNSXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateNSXMouseExited(evt);
            }
        });
        btnUpdateNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNSXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnNSXLayout = new javax.swing.GroupLayout(jpnNSX);
        jpnNSX.setLayout(jpnNSXLayout);
        jpnNSXLayout.setHorizontalGroup(
            jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNSXLayout.createSequentialGroup()
                .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNSXLayout.createSequentialGroup()
                        .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnNSXLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnNSXLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnNewNSX)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddNSX)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateNSX)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnExitNSX)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNSXLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnNSXLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(btnFirstNSX)
                            .addGap(18, 18, 18)
                            .addComponent(btnPreNSX)
                            .addGap(18, 18, 18)
                            .addComponent(txtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnNextNSX)
                            .addGap(18, 18, 18)
                            .addComponent(btnLastNSX))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnNSXLayout.createSequentialGroup()
                    .addGap(765, 765, 765)
                    .addComponent(jLabel26)
                    .addContainerGap(740, Short.MAX_VALUE)))
        );
        jpnNSXLayout.setVerticalGroup(
            jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNSXLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewNSX)
                    .addComponent(btnExitNSX)
                    .addComponent(btnFirstNSX)
                    .addComponent(btnNextNSX)
                    .addComponent(btnPreNSX)
                    .addComponent(btnLastNSX)
                    .addComponent(txtRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddNSX)
                    .addComponent(btnDeleteNSX)
                    .addComponent(btnUpdateNSX))
                .addContainerGap())
            .addGroup(jpnNSXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnNSXLayout.createSequentialGroup()
                    .addGap(354, 354, 354)
                    .addComponent(jLabel26)
                    .addContainerGap(374, Short.MAX_VALUE)))
        );

        Tabbed.addTab("Cập nhật nhà sản xuất", jpnNSX);

        getContentPane().add(Tabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1510, 760));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Quản lý Kho");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 381, 65));

        panelThem.setBackground(new java.awt.Color(102, 102, 255));

        lblAnhAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/account_120px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Xin chào");

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setAutoscrolls(true);

        btnDangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/dang_xuat.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tìm kiếm :");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelThemLayout = new javax.swing.GroupLayout(panelThem);
        panelThem.setLayout(panelThemLayout);
        panelThemLayout.setHorizontalGroup(
            panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemLayout.createSequentialGroup()
                .addGroup(panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThemLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnhAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelThemLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelThemLayout.createSequentialGroup()
                .addGroup(panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThemLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnDangxuat))
                    .addGroup(panelThemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelThemLayout.setVerticalGroup(
            panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAnhAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                .addComponent(btnDangxuat)
                .addGap(22, 22, 22))
        );

        getContentPane().add(panelThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 0, 270, -1));

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/return_30px.png"))); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAnhActionPerformed
        lblAnhDaiDien.setIcon(new ImageIcon(getClass().getResource("")));
    }//GEN-LAST:event_btnXoaAnhActionPerformed

    private void txtChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChooseFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        String choosertitle = null;
        chooser.setDialogTitle(choosertitle);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, PNG & GIF Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            String dirr = "" + chooser.getCurrentDirectory();
            File file = chooser.getSelectedFile();

            if (dirr.substring(dirr.length() - 1, dirr.length()).equals(".")) {
                dirr = dirr.substring(0, dirr.length() - 1);
                String sourceFolder = "" + dirr + "" + file.getName();
            } else {
                String sourceFolder = "" + dirr + "/" + file.getName();
            }

        } else {
        }
        String sourceFolder = null;
        lblAnhDaiDien.setIcon(new ImageIcon(sourceFolder));
    }//GEN-LAST:event_txtChooseFileActionPerformed

    private void tblDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDienThoaiMouseClicked
        new DangNhapFrame().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_tblDienThoaiMouseClicked

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed

    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnExitDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitDTMouseEntered
//        btnExitDT.setBackground(new Color(255, 0, 153));
//        btnExitDT.setForeground(Color.white);
    }//GEN-LAST:event_btnExitDTMouseEntered

    private void btnExitDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitDTMouseExited
//        btnExitDT.setBackground(new Color(240, 240, 240));
//        btnExitDT.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnExitDTMouseExited

    private void btnUpdateDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateDTMouseEntered
//        btnUpdateDT.setBackground(new Color(255, 0, 153));
//        btnUpdateDT.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDTMouseEntered

    private void btnUpdateDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateDTMouseExited
//        btnUpdateDT.setBackground(new Color(240, 240, 240));
//        btnUpdateDT.setForeground(Color.black);
    }//GEN-LAST:event_btnUpdateDTMouseExited

    private void btnNewDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewDTMouseEntered
//        btnNewDT.setBackground(new Color(255, 0, 153));
//        btnNewDT.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewDTMouseEntered

    private void btnNewDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewDTMouseExited
//        btnNewDT.setBackground(new Color(240, 240, 240));
//        btnNewDT.setForeground(Color.black);      // TODO add your handling code here:
    }//GEN-LAST:event_btnNewDTMouseExited

    private void btnDeleteDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteDTMouseEntered
//        btnDeleteDT.setBackground(new Color(255, 0, 153));
//        btnDeleteDT.setForeground(Color.white);    // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteDTMouseEntered

    private void btnDeleteDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteDTMouseExited
//        btnDeleteDT.setBackground(new Color(240, 240, 240));
//        btnDeleteDT.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteDTMouseExited

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        new GiaoDienChinhNhanVienFrame("Hello").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnAddDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDTMouseEntered
//        btnAddDT.setBackground(new Color(255, 0, 153));
//        btnAddDT.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDTMouseEntered

    private void btnAddDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDTMouseExited
//        btnAddDT.setBackground(new Color(240, 240, 240));
//        btnAddDT.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDTMouseExited

    private void btnAddDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDTActionPerformed

    private void btnExitNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitNSXActionPerformed
        // TODO add your handling code here:
        new GiaoDienChinhNhanVienFrame(url).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitNSXActionPerformed

    private void btnExitNSXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitNSXMouseExited
        //        btnExitNSX.setBackground(new Color(240, 240, 240));
        //        btnExitNSX.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnExitNSXMouseExited

    private void btnExitNSXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitNSXMouseEntered
        //        btnExitNSX.setBackground(new Color(255, 0, 153));
        //        btnExitNSX.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnExitNSXMouseEntered

    private void btnAddNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNSXActionPerformed
        // TODO add your handling code he 
        int tong = tblNSX.getRowCount();
        String patternemail = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String pattersdt = "^0\\d{9}$";
           if (txt_manhasanxuat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty");
            txt_manhasanxuat.requestFocus();
            return;
        }
        if (txt_tennhasanxuat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty");
            txt_tennhasanxuat.requestFocus();
            return;
        }
        if (txt_diachinhasanxuat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty");
            txt_diachinhasanxuat.requestFocus();
            return;
        }
        if (txt_dienthoainhasanxuat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty");
            txt_dienthoainhasanxuat.requestFocus();
            return;
        }
        if (txt_emailnhasanxuat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty");
            txt_emailnhasanxuat.requestFocus();
            return;
        }
        if (!txt_emailnhasanxuat.getText().matches(patternemail)) {
            JOptionPane.showMessageDialog(this, "email error");
            txt_emailnhasanxuat.requestFocus();
            return;
        }
        if(!txt_dienthoainhasanxuat.getText().matches(pattersdt)){
            JOptionPane.showMessageDialog(this,"so dien thoai phai tu 0 den 10 so");
            txt_dienthoainhasanxuat.requestFocus();
            return; 
        }
        for (int i = 0; i < tong; i++) {
            String manhasanxuat = (String) tblNSX.getValueAt(i, 0);
            String email=(String) tblNSX.getValueAt(i,4);
            if (txt_manhasanxuat.getText().equals(manhasanxuat)) {
                JOptionPane.showMessageDialog(this, "ma nay da co");
                return;
            }
            if(txt_emailnhasanxuat.getText().equals(email)){
                JOptionPane.showMessageDialog(this,"email nay da co");
                return;
            }
        }
        try {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            String sql = "insert into nhasanxuat(manhasanxuat,tennhasanxuat,diachi,dienthoai,email,motathem,hinh) values(?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1, txt_manhasanxuat.getText());
            stm.setString(2, txt_tennhasanxuat.getText());
            stm.setString(3, txt_diachinhasanxuat.getText());
            stm.setString(4, txt_dienthoainhasanxuat.getText());
            stm.setString(5, txt_emailnhasanxuat.getText());
            stm.setString(6, txt_ghichunhasanxuat.getText());
            stm.setString(7, filenamepic);
            stm.execute();
            //            stm.close();
            //            con.close();
            
       
            loadtotable_nhasanxuat();
            reset();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddNSXActionPerformed

    private void btnAddNSXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNSXMouseExited
        //        btnAddNSX.setBackground(new Color(240, 240, 240));
        //        btnAddNSX.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNSXMouseExited

    private void btnAddNSXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNSXMouseEntered
        //        btnAddNSX.setBackground(new Color(255, 0, 153));
        //        btnAddNSX.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNSXMouseEntered

    private void btnDeleteNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNSXActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            String sql = "delete from nhasanxuat where manhasanxuat=?";
            PreparedStatement ps = null;
            ps = con.prepareStatement(sql);
            ps.setString(1, txt_manhasanxuat.getText().trim());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "xóa thành công");
            ps.close();
            con.close();
            loadtotable_nhasanxuat();
            reset();
            System.out.println("4");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteNSXActionPerformed

    private void btnDeleteNSXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNSXMouseExited
        //        btnDeleteNSX.setBackground(new Color(240, 240, 240));
        //        btnDeleteNSX.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteNSXMouseExited

    private void btnDeleteNSXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNSXMouseEntered
        //        btnDeleteNSX.setBackground(new Color(255, 0, 153));
        //        btnDeleteNSX.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteNSXMouseEntered

    private void btnUpdateNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNSXActionPerformed
        // TODO add your handling code here:
        String patternemail = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String pattersdt = "^0\\d{9}$";
        if (!txt_emailnhasanxuat.getText().matches(patternemail)) {
            JOptionPane.showMessageDialog(this, "email khong dung cu phap");
            txt_emailnhasanxuat.requestFocus();
            return;
        }
        if (!txt_dienthoainhasanxuat.getText().matches(pattersdt)) {
            JOptionPane.showMessageDialog(this, "sdt khong dung cu phap");
            txt_dienthoainhasanxuat.requestFocus();
            return;
        }
        try {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            String sql = "update nhasanxuat set tennhasanxuat=?,diachi=?,dienthoai=?,email=?,motathem=?,hinh=?";
            PreparedStatement stm = con.prepareStatement(sql);
            //            stm.setString(1, txt_manhasanxuat.getText().trim());
            stm.setString(1, txt_tennhasanxuat.getText().trim());
            stm.setString(2, txt_diachinhasanxuat.getText().trim());
            stm.setString(3, txt_dienthoainhasanxuat.getText().trim());
            stm.setString(4, txt_emailnhasanxuat.getText().trim());
            stm.setString(5, txt_ghichunhasanxuat.getText().trim());
            stm.setString(6, filenamepic.trim());
            stm.execute();
            stm.close();
            con.close();
            loadtotable_nhasanxuat();
            //            filldata(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            File file = new File(filenamepic);
            FileInputStream fis = new FileInputStream(file);
            byte[] image = new byte[(int) file.length()];
            fis.read(image);
            String sql1 = "update nhasanxuat set hinh=? where manhasanxuat='" + txt_manhasanxuat.getText() + "'";
            PreparedStatement pst = con.prepareStatement(sql1);
            pst = con.prepareStatement(sql1);
            pst.setBytes(1, image);
            pst.executeQuery();
            pst.close();
            JOptionPane.showMessageDialog(this, "oke");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUpdateNSXActionPerformed

    private void btnUpdateNSXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateNSXMouseExited
        //        btnUpdateNSX.setBackground(new Color(240, 240, 240));
        //        btnUpdateNSX.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateNSXMouseExited

    private void btnUpdateNSXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateNSXMouseEntered
        //        btnUpdateNSX.setBackground(new Color(255, 0, 153));
        //        btnUpdateNSX.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateNSXMouseEntered

    private void btnLastNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastNSXActionPerformed
        // TODO add your handling code here:
        tblNSX.setRowSelectionInterval(tblNSX.getRowCount()-1,tblNSX.getRowCount()-1);
        updaterecord();
        tblNSXMouseClicked(null);
    }//GEN-LAST:event_btnLastNSXActionPerformed

    private void btnNextNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextNSXActionPerformed
        // TODO add your handling code here:
        int choice=tblNSX.getSelectedRow();
        if(choice==tblNSX.getRowCount()-1){
            choice=-1;
        }
        tblNSX.setRowSelectionInterval(choice+1,choice+1);
        updaterecord();
        tblNSXMouseClicked(null);
    }//GEN-LAST:event_btnNextNSXActionPerformed

    private void btnPreNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreNSXActionPerformed
        // TODO add your handling code here:
        int choice=tblNSX.getSelectedRow();
        if(choice==0 || choice==-1){
            choice=tblNSX.getRowCount();
        }
        tblNSX.setRowSelectionInterval(choice-1,choice-1);
        updaterecord();
        tblNSXMouseClicked(null);
    }//GEN-LAST:event_btnPreNSXActionPerformed

    private void btnFirstNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstNSXActionPerformed
        // TODO add your handling code here:
        tblNSX.setRowSelectionInterval(0,0);
        updaterecord();
        tblNSXMouseClicked(null);
    }//GEN-LAST:event_btnFirstNSXActionPerformed

    private void btnNewNSXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewNSXMouseExited
        //        btnNewNSX.setBackground(new Color(240, 240, 240));
        //        btnNewNSX.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_btnNewNSXMouseExited

    private void btnNewNSXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewNSXMouseEntered
        //         btnNewNSX.setBackground(new Color(255, 0, 153));
        //         btnNewNSX.setForeground(Color.white);          // TODO add your handling code here:
    }//GEN-LAST:event_btnNewNSXMouseEntered

    private void tblNSXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNSXMouseClicked
        // TODO add your handling code here
        int row=tblNSX.getSelectedRow();
        filldata(row);
        updaterecord();
         sort();
    }//GEN-LAST:event_tblNSXMouseClicked

    private void txtChooseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChooseFile1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String fullpath = file.getAbsolutePath();
            filenamepic = chooser.getSelectedFile().getName();
            uphinh(fullpath);
            try {
                Path src = Paths.get(fullpath);
                Path desk = Paths.get("src\\Img_Icon\\" + filenamepic);
                    Files.copy(src, desk, StandardCopyOption.REPLACE_EXISTING);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_txtChooseFile1ActionPerformed

    private void txtChooseFile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChooseFile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChooseFile1MouseClicked

    private void lbl_anhdaidiennhasanxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anhdaidiennhasanxuatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_anhdaidiennhasanxuatMouseClicked

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped

    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
           DefaultTableModel table=(DefaultTableModel)tblNSX.getModel(); 
           String search=txtTimKiem.getText();
           TableRowSorter<DefaultTableModel>tr=new TableRowSorter<DefaultTableModel>(table); 
            tblNSX.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_QuanLyKhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_QuanLyKhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_QuanLyKhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_QuanLyKhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_QuanLyKhoFrame().setVisible(true);
            }
        });
    }
public void loadtotable_nhasanxuat(){
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        try {
            conn = DriverManager.getConnection(url);
            String sql = "select * from nhasanxuat";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            Vector nsx = null;
            table_nhasanxuat.setRowCount(0);
//        if (rs.isBeforeFirst() == false) {
//            JOptionPane.showMessageDialog(this, "chua co sinh vien nao");
//            return;
//        }
            while (rs.next()) {
                nsx = new Vector();
                nsx.add(rs.getString("manhasanxuat"));
                nsx.add(rs.getString("tennhasanxuat"));
                nsx.add(rs.getString("diachi"));
                nsx.add(rs.getString("dienthoai"));
                nsx.add(rs.getString("email"));
                nsx.add(rs.getString("motathem"));
                nsx.add(rs.getString("hinh"));
                table_nhasanxuat.addRow(nsx);
            }
            tblNSX.setModel(table_nhasanxuat);
            conn.close();
            st.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
public void filldata(int row){
    if(row<0){
        return;
    }
    txt_manhasanxuat.setText(tblNSX.getValueAt(row,0).toString());
    txt_tennhasanxuat.setText(tblNSX.getValueAt(row,1).toString());
    txt_diachinhasanxuat.setText(tblNSX.getValueAt(row,2).toString());
    txt_dienthoainhasanxuat.setText(tblNSX.getValueAt(row,3).toString());
    txt_emailnhasanxuat.setText(tblNSX.getValueAt(row,4).toString());
    txt_ghichunhasanxuat.setText(tblNSX.getValueAt(row,5).toString());
    uphinh(tblNSX.getValueAt(row,6).toString()); 
} 
public void reset(){
    txt_manhasanxuat.setText("");
    txt_tennhasanxuat.setText("");
    txt_diachinhasanxuat.setText("");
    txt_dienthoainhasanxuat.setText("");
    txt_emailnhasanxuat.setText("");
    txt_ghichunhasanxuat.setText("");
}
public void uphinh(String hinh){
    ImageIcon image=new ImageIcon("src\\Img_Icon\\"+hinh); 
    Image im=image.getImage();
    ImageIcon icon=new ImageIcon(im.getScaledInstance(lbl_anhdaidiennhasanxuat.getWidth(),lbl_anhdaidiennhasanxuat.getHeight(),im.SCALE_SMOOTH)); 
    lbl_anhdaidiennhasanxuat.setIcon(icon);  
}
public void sort(){
    TableRowSorter <DefaultTableModel> sorter=new TableRowSorter<DefaultTableModel>(table_nhasanxuat);
    tblNSX.setRowSorter(sorter);
}
public void updaterecord() {
        txtRecord.setText("Record:" + (String.valueOf(tblNSX.getSelectedRow())+" "+ "of "+" " +tblNSX.getRowCount()));
    }
public void checknull(){
    if(txt_manhasanxuat.getText().equals("")){
        txt_manhasanxuat.requestFocus();
        return; 
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabbed;
    private javax.swing.JButton btnAddDT;
    private javax.swing.JButton btnAddNSX;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnDeleteDT;
    private javax.swing.JButton btnDeleteNSX;
    private javax.swing.JButton btnExitDT;
    private javax.swing.JButton btnExitNSX;
    private javax.swing.JButton btnFirstDT;
    private javax.swing.JButton btnFirstNSX;
    private javax.swing.JButton btnLastDT;
    private javax.swing.JButton btnLastNSX;
    private javax.swing.JButton btnNewDT;
    private javax.swing.JButton btnNewNSX;
    private javax.swing.JButton btnNextDT;
    private javax.swing.JButton btnNextNSX;
    private javax.swing.JButton btnPreNSX;
    private javax.swing.JButton btnPreviousDT;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUpdateDT;
    private javax.swing.JButton btnUpdateNSX;
    private javax.swing.JButton btnXoaAnh;
    private javax.swing.JComboBox<String> cboBaoHanhDT;
    private javax.swing.JComboBox<String> cboHDH;
    private javax.swing.JComboBox<String> cboMangDT;
    private javax.swing.JComboBox<String> cboRamDT;
    private javax.swing.JComboBox<String> cboSacDT;
    private javax.swing.JComboBox<String> cboSimDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpnNSX;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAnhAccount;
    private javax.swing.JLabel lblAnhDaiDien;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblIndexDT;
    private javax.swing.JLabel lblLenghDT;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblRecorđT;
    private javax.swing.JLabel lbl_anhdaidiennhasanxuat;
    private javax.swing.JPanel panelThem;
    private javax.swing.JPanel pnltructhuoc;
    private javax.swing.JPanel pnltructhuoc2;
    private javax.swing.JTable tblDienThoai;
    private javax.swing.JTable tblNSX;
    private javax.swing.JButton txtChooseFile;
    private javax.swing.JButton txtChooseFile1;
    private javax.swing.JTextField txtMaDT;
    private javax.swing.JTextArea txtMoTaDT;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JLabel txtRecord;
    private javax.swing.JTextField txtSoLuongTonDT;
    private javax.swing.JTextField txtTenDT;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txt_diachinhasanxuat;
    private javax.swing.JTextField txt_dienthoainhasanxuat;
    private javax.swing.JTextField txt_emailnhasanxuat;
    private javax.swing.JTextArea txt_ghichunhasanxuat;
    private javax.swing.JTextField txt_manhasanxuat;
    private javax.swing.JTextField txt_tennhasanxuat;
    // End of variables declaration//GEN-END:variables
}
