/*
/*
/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien_NhanVien;

import GiaoDien_QuanLy.*;
import java.awt.Color;
import java.awt.Cursor;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Dell
 */
public class GiaoDienChinhNhanVienFrame extends javax.swing.JFrame {
Thread dongho;
    /**
     * Creates new form gaiodien1
     */
    public GiaoDienChinhNhanVienFrame(String CurrentUser) {
        initComponents();
        lblBanHang.setIconTextGap(20);
        lblQuanLyKho.setIconTextGap(20);
        lblKhachHang.setIconTextGap(20);
        lblQuanLyKho.setIconTextGap(20);
        lblAccount.setText("Trương Anh Thọ");
        ImageIcon ig=new ImageIcon(getClass().getResource("/Img_Icon/iconfram.png"));
        setIconImage(ig.getImage());
        lblQuanLyKho.setOpaque(true);
        lblBanHang.setOpaque(true);
        lblDangXuat.setOpaque(true);
        lblKhachHang.setOpaque(true);
        loadDongHo();
        getContentPane().setBackground(new Color(252,252,252));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelheader = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMid = new javax.swing.JPanel();
        lblBanHang = new javax.swing.JLabel();
        lblQuanLyKho = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");
        setResizable(false);

        panelheader.setBackground(new java.awt.Color(26, 52, 158));

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccount.setText("Acount");
        lblAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/account_120px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_GiaoDienChinh/logo.png"))); // NOI18N
        jLabel2.setText("QUẢN LÝ BÁN HÀNG");

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccount)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMid.setBackground(new java.awt.Color(255, 255, 255));
        panelMid.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        lblBanHang.setBackground(new java.awt.Color(242, 242, 242));
        lblBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_GiaoDienChinh/giohangxanh.png"))); // NOI18N
        lblBanHang.setText("Bán Hàng");
        lblBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBanHang.setInheritsPopupMenu(false);
        lblBanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBanHangMouseExited(evt);
            }
        });
        panelMid.add(lblBanHang);

        lblQuanLyKho.setBackground(new java.awt.Color(242, 242, 242));
        lblQuanLyKho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_GiaoDienChinh/phonexanh.png"))); // NOI18N
        lblQuanLyKho.setText("Quản Lý Kho");
        lblQuanLyKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuanLyKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuanLyKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblQuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyKhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuanLyKhoMousePressed(evt);
            }
        });
        panelMid.add(lblQuanLyKho);

        lblKhachHang.setBackground(new java.awt.Color(242, 242, 242));
        lblKhachHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_GiaoDienChinh/khachhangxanh.png"))); // NOI18N
        lblKhachHang.setText("Khách Hàng");
        lblKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseExited(evt);
            }
        });
        panelMid.add(lblKhachHang);

        lblDangXuat.setBackground(new java.awt.Color(242, 242, 242));
        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_GiaoDienChinh/dangxuatxanh.png"))); // NOI18N
        lblDangXuat.setText("Đăng Xuất");
        lblDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });
        panelMid.add(lblDangXuat);

        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseEntered
        lblBanHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblBanHang.setBackground(new Color(66,61,241));   
        lblBanHang.setForeground(Color.white);  
        lblBanHang.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/giohangtrang.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_lblBanHangMouseEntered

    private void lblBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseExited
        lblBanHang.setBackground(new Color(242,242,242));
        lblBanHang.setForeground(Color.black);  
        lblBanHang.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/giohangxanh.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lblBanHangMouseExited

    private void lblQuanLyKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyKhoMouseEntered
        lblQuanLyKho.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblQuanLyKho.setBackground(new Color(66,61,241));
        lblQuanLyKho.setForeground(Color.white);  
        lblQuanLyKho.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/phonetrang.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyKhoMouseEntered

    private void lblQuanLyKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyKhoMouseExited
        lblQuanLyKho.setBackground(new Color(242,242,242));
        lblQuanLyKho.setForeground(Color.black);  
        lblQuanLyKho.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/phonexanh.png")));     // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyKhoMouseExited

    private void lblKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseEntered
        lblBanHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblKhachHang.setBackground(new Color(66,61,241));
        lblKhachHang.setForeground(Color.white);  
        lblKhachHang.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/khachhangtrang.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_lblKhachHangMouseEntered

    private void lblKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseExited
        lblKhachHang.setBackground(new Color(242,242,242));
        lblKhachHang.setForeground(Color.black);  
        lblKhachHang.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/khachhangxanh.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_lblKhachHangMouseExited

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
           // TODO add your handling code here:
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        lblBanHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblDangXuat.setBackground(new Color(66,61,241));
        lblDangXuat.setForeground(Color.white);  
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/dangxuattrang.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        lblDangXuat.setBackground(new Color(242,242,242));
        lblDangXuat.setForeground(Color.black);  
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/Img_GiaoDienChinh/dangxuatxanh.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblQuanLyKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyKhoMousePressed
        new B_QuanLyKhoFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQuanLyKhoMousePressed

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseClicked
        new A_BanHangFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBanHangMouseClicked
    public void loadDongHo() {
            dongho = new Thread() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            Date d = new Date();
                            SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss aa");
                            String time = f.format(d);
                            lblDongHo.setText(time);
                            Thread.sleep(1000);
                        } catch (Exception ex) {
                            break;
                        }
                    }
                }
            };
            dongho.start();
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinhNhanVienFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblQuanLyKho;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelheader;
    // End of variables declaration//GEN-END:variables
}
