/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien_QuanLy;


import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Tho
 */
public class B_FullTableNhanVienFrame extends javax.swing.JFrame {

    
    public B_FullTableNhanVienFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIcontitle();
        getContentPane().setBackground(new Color(245,245,245));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrll = new javax.swing.JScrollPane();
        tblFullTable = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setTitle("Bảng Nhân Viên");

        tblFullTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblFullTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblFullTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username","Password", "Họ và tên"
                , "Học vấn", "Ngày vào làm"
                , "Giới tính", "Điện thoại"
                , "Ngày sinh", "Lương", "CMND"
                ,"Địa chỉ",

            }
        ));
        tblFullTable.setAlignmentX(100.0F);
        tblFullTable.setAlignmentY(500.0F);
        jscrll.setViewportView(tblFullTable);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 102, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Icon/lap_lai.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrll, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscrll, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
   
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
//     */
    public static void main(String args[]) {
//       FullTable fl=new FullTable();
//       fl.setVisible(true);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(Exception e){}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new B_FullTableNhanVienFrame().setVisible(true);
        });
    }
    public void setIcontitle(){
        ImageIcon ig=new ImageIcon(getClass().getResource("/Img_Icon/iconfram.png"));
                setIconImage(ig.getImage());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jscrll;
    private javax.swing.JTable tblFullTable;
    // End of variables declaration//GEN-END:variables
}
